env:
- CI=false npm run build
language: node_js
node_js:
- node
jobs:
  include:
  - name: deploy_dev_prod_lambdas
    if: branch IN (master, development)
    before_install:
      - pip install boto3 --user
      - pip install pynpm --user
    script: ./Automation/TravisScripts/deployLambdas.py
  - name: deploy_feature-lambdas
    if: branch =~ /^feature-sprint[0-9]-api/
    before_install:
    - PATH_TO_LAMBDA=$(./Automation/TravisScripts/setPathToLambda.sh)
    - cd $PATH_TO_LAMBDA
    deploy:
      provider: lambda
      function_name: $TRAVIS_BRANCH
      region: "us-west-2"
      role: "arn:aws:iam::061431082068:role/Lambda_Role"
      runtime: "nodejs12.x"
      handler_name: "handler"
      access_key_id: "$AWS_ACCESS_KEY2_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
      on:
        repo: North-Seattle-College/ad440-winter2020-thursday-repo
        branch: $TRAVIS_BRANCH
    branches:
      only:
      - $TRAVIS_BRANCH
  - name: deploy_prod_s3
    if: branch = master
    before_install:
    - "./Automation/TravisScripts/build_env.sh"
    - cd UI/
    script:
    - npm run build
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$AWS_ACCESS_KEY2_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
      bucket: www.2edusite.com
      acl: bucket_owner_full_control
      region: us-west-2
      local_dir: build
      on:
        repo: North-Seattle-College/ad440-winter2020-thursday-repo
        branch: $TRAVIS_BRANCH
    branches:
      only:
      - $TRAVIS_BRANCH
  - name: deploy_dev_s3
    if: branch = development
    before_install:
    - "./Automation/TravisScripts/build_env.sh"
    - cd UI/
    script:
    - npm run build
    deploy:
      skip_cleanup: true
      provider: s3
      access_key_id: "$AWS_ACCESS_KEY2_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
      bucket: www-dev.2edusite.com #for the purposes of using in demo it deploys it on production s3 bucket
      acl: bucket_owner_full_control
      region: us-west-2
      local_dir: build
      on:
        repo: North-Seattle-College/ad440-winter2020-thursday-repo
        branch: $TRAVIS_BRANCH
    branches:
      only:
      - $TRAVIS_BRANCH
