language: node_js
node_js:
- node
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  bucket: bucketostuffs
  acl: public_read
  region: us-west-2
  on:
    repo: North-Seattle-College/ad440-winter2020-thursday-repo
    branch: feature-sprint1-michael
branches:
  only:
  - feature-sprint1-michael
  local_dir: build
env:
  global:
  - secure: exPzeiTydEKiVH8ue2AJGO5ycyVIvXXwH6pqbC/bzWeOPrQEbEX+GTELCYsTS1Wk42eoOyBqo0dsm4ap29nLa8grShlTSRtkib1f1GhV4bZbk9bPrcfCIqi3nBcUf+AgwYR3iB+4i2sFhq3EZWyntYSKNZbrctJb2NkCRYH2ijKKtZT4QgQc4t6TppUiAMM2D5eNOF5gIbULKVIRdv4HyRdoz9rd5z1+MLVAH9jgH7jgSjKZFETiECoPHJB8kb7/9Xzv2Jwmhyz7MX0h2uf2pCyqwkBo3LOax8O66fK2CJMAlDkdXtTOYTxvDJZVANNCW0i/jiyfzntO/+gP5foIrviVvtlNcubQ5z6Evei/AfEKIk5/nwaRx8jTfUuAAzSrETPovQqZkZxVo67Ib7e3Al+t8HC/gIoJeICDiPKYF8IRcTZeoNRxW0EAz8ehyJJhanXlN7X5LJrsnuVfQl4in8OX74ozdgX8XWA5fWBU403IOxh7oTU8AWLAf44tmuT+4FDVNKh9FOnWiAQwi5qr6VtjXuIa1W4pmGbOu4eLZ0KZoMPUrHUX8ZIwn0ud6d7ozlGsiuYlPIrNLtX6H2rhvkilOt4hDHieHUwSrYtNRTgpjMoOA4i8owMGhmEmp36z+ud4FJ1ub9MYoSQbYsyXwTwHdpFSatmXF+5kxMD+BYQ=
  - secure: p7u3x43M4vzkqJdqdYQhNSIgj1g69lB03XUYpL3lbNfCqcfPL4GTydrnU7JqTmxyi2mjlweEnO5dckImzVoB+VzlS3T9yMg0zE4AsocXiQaYSfy/iVgFuFwtJnv26SRNo+/2cXhYIuIagCyczsmosPsyH9MnHewHlG9uEeuDYMy1V7mxhh4k+Qgos/q+Jl8lTGGmufOIK1cQIo0oys9VSVgppWRfCtwy1H7vDlKCsDwFgFG/vn05WImmcNUE4GZzK6+G/S+8trvumKi0Nbus+IVUPAscrz+RH8r2EGqs41m8SiM005ZAw7EHUNEIBA7dRPgAq0eTSXwrwmjOo+BCPjpVZZXflM408BARxrKgg8LNqmjjfWBGEdwuR2147GRWPVNS0Bmrc8zigdwfDlbG4LJuxrMoBFCl4Zo3PNFzs4IQFgNgixIT2auIHXm+63UWXUaKc5m0zugkaGoP0BFKSlSXErUZ87usNr0COKF0Zp0mHFWZdGX3wi21a7PC/K3AdfkFqskIfmi6RfThT9FUmiSAX+hC+187JtgZF7meNH7Jiq98XvUznEhmnJPS/jVgGwGUNcKE2B0mT/0eC1bjBFlPfXIaVNpGXDJjUrIn+kC2fNWi9yFBBmh5+jpb0bNNWoy1rBh/DfEXDEze6Ym9rGdNm0Y0c9TeRx2LnFd5SOQ=
