language: node_js
node_js:
- node
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: bucketostuffs
  acl: bucket_owner_full_control
  region: us-west-2
  on:
    repo: North-Seattle-College/ad440-winter2020-thursday-repo
branches:
  only:
  - feature-sprint1-michael