env:
- CI=false npm run build
language: node_js
node_js:
- node
jobs:
  include:
  - name: deploy_s3_dev
    before_install:
    - cd UI/												#repo location
    script:															#terminal commands to run npm
    - npm run build 												#build build file
    deploy:
      skip_cleanup: true											#dont remove build files
      provider: s3													#Login to aws with credentials
      access_key_id: "$AWS_ACCESS_KEY2_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
      bucket: www-dev.2edusite.com									#denotes bucket name to deploy to
      acl: bucket_owner_full_control
      region: us-west-2
      local_dir: build												#deploy only build directory
      on:
        repo: North-Seattle-College/ad440-winter2020-thursday-repo	#start deployment branch anytime a pull or push
        branch: development
  - name: deploy_s3_prod
    before_install:
    - cd UI											
    script:															
    - npm run build 												
    deploy:
      skip_cleanup: true											
      provider: s3													
      access_key_id: "$AWS_ACCESS_KEY2_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
      bucket: www.2edusite.com							
      acl: bucket_owner_full_control
      region: us-west-2
      local_dir: build												
      on:
        repo: North-Seattle-College/ad440-winter2020-thursday-repo	
        branch: master       
  - name: deploy_s3_feature
    before_install:
    - cd UI												
    script:															
    - npm run build 												
    deploy:
      skip_cleanup: true											
      provider: s3													
      access_key_id: "$AWS_ACCESS_KEY2_ID"
      secret_access_key: "$AWS_SECRET_ACCESS_KEY2"
      bucket: www-feature.2edusite.com								
      acl: bucket_owner_full_control
      region: us-west-2
      local_dir: build												
      on:
        repo: North-Seattle-College/ad440-winter2020-thursday-repo
        all_branches: true
