language: node_js
node_js:
- node
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  provider: s3
  bucket: bucketostuffs
  acl: public_read
  region: us-west-2
  on:
    repo: North-Seattle-College/ad440-winter2020-thursday-repo
    branch: feature-sprint1-michael
branches:
  only:
  - feature-sprint1-michael
  local_dir: build
