swagger: "2.0"
info:
  description: "Property Management Add Property"
  version: "1.0.0"
  title: "Add Property"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "kvn.law1@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/v1"
tags:
- name: "property"
  description: "Propertiees of Property Management"

schemes:
- "http"
paths:
  /property:
    post:
      tags:
      - "property"
      summary: "Add a property to the Property Management"
      description: "Creates a new Property"
      operationId: "addProperty"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Property object that needs to be added to the Database"
        required: true
        schema:
          $ref: "#/definitions/Property"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/Property"
        405:
          description: "Method Not Allowed"    

 
definitions:
  Property:
    type: "object"
    properties:
      property_id:
        type: "integer"
        format: "int64"
      property_name:
        type: "string"
        format: "string"
      property_type:
        type: "string"
        format: "string"
      property_address:
        type: "string"
        format: "string"
      property_city:
        type: "string"
        format: "string"
      property_state:
        type: "string"
        format: "string"
      property_zip:
        type: "integer"
        format: "int64"  
      propert_country:
        type: "string"
        format: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"